name: Slayers
version: ${project.version}
main: net.maploop.Slayers
api-version: 1.16
authors: [ Maploop ]
description: Hypixel Skyblock Slayers
website: deemu.net
commands:
  slayer:
  slimetest:
  magmaboss:
  privatevault:
    aliases:
      - pv
  wipevault:
  spawnboss:
